### ISSUE TITLE
Parameters declared in `components` don't retain `required: true`

### ISSUE THREAD

**Issue by kelnos** [guardrail-dev/guardrail#1313]
If we declare a parameter in this way:
```yaml
components:
  parameters:
    SomeHeader:
      - name: SomeHeader
        in: header
        required: true
        schema:
          type: string
```
And then use it somewhere:
```yaml
paths:
  /foo:
    get:
      parameters:
        - $ref: "#/components/parameters/SomeHeader"
```
Then the result will _not_ be required.  Adding `required: true` parallel to the `$ref` line seems not to work either.  Inlining the definition _does_ work.
