### ISSUE TITLE
Default values are ignored

### ISSUE THREAD

**Issue by andiskrauklis** [guardrail-dev/guardrail#1427]
I'm having a problem with a default value.

`version: sbt-guardrail:0.69.0.1`

Definition
```yaml
properties:
  fieldOne:
    type: String
  fieldTwo:
    type: Boolean
    default: false
```

Generated code
```scala
case class Something(fieldOne: String, fieldTwo: Boolean = false)
```

So far, so good.

However, once I `POST` JSON without a value
```json
{
  "fieldOne": "test"
}
```
I get the error
`Attempt to decode value on failed cursor: DownField(fieldTwo)`
