### ISSUE TITLE
Query parameters with defaults generate `Option`al values

### ISSUE THREAD

**Issue by lolgab** [guardrail-dev/guardrail#1532]
When you have a query parameter like:
```yaml
  limitParam: &limitParam
    in: query
    name: limit
    required: false
    type: integer
    format: int32
    default: 100
```

It generates an `Option`al parameter. Instead, it should not wrap with `Option` since the value has a default.

Current behavior:
`limit: Option[Int] = Option(100)` 

Desired behavior:
`limit: Int = 100` 

Of course this is a breaking change, so it should go under a flag to avoid breaking existing code.
