### ISSUE TITLE
Gracefully handle or ignore properties that do not have a type

### ISSUE THREAD

**Issue by alexklibisz** [guardrail-dev/guardrail#1550]
Hi, is there a way to gracefully handle or ignore properties that do not have a type?

For example, some properties in the [Google Maps openapi specification](https://github.com/googlemaps/openapi-specification/releases/tag/v1.17.16) are missing a `type`. If you download the release I linked, you'll see an example on line 23140, where a property only has a `description`:

```yaml
properties:
  steps:  
    description: Contains detailed directions for walking or driving steps in transit directions. Substeps are only available when travel_mode is set to "transit". The inner steps array is of the same type as steps.
```

Despite it being pretty useless, it seems like this is might actually be a valid property, as per: https://swagger.io/docs/specification/data-models/data-types/#any
