### ISSUE TITLE
path parameters in $refs are not picked up

### ISSUE THREAD

**Issue by martijnhoekstra** [guardrail-dev/guardrail#1579]
given

main.yml:
```
paths:
  /my/{path}/somewhere:
    $ref: external.yml#/~1my~1{path}~1somewhere
 ```
 
external.yml:

```
/my/{path}/somewhere:
  parameters:
  - in: path
     name: path
     required: true
  get:
    operationId: myExternalOp
    resonses:
      '200':
        description: ok
```

no route parameter for path is created in the handler interface
