### ISSUE TITLE
Never empty collectionFormat: multi

### ISSUE THREAD

**Issue by rtfpessoa** [guardrail-dev/guardrail#210]
When I have a parameter like:
```
parameters:
        - in: query
          name: fileIds
          description: File identifiers
          required: false
          type: array
          items:
            type: integer
            format: int64
          # HACK: Force type Long
          x-scala-type: 'Iterable[Long]'
          collectionFormat: multi
```

In the handler it generates something like `Option[Iterable[Long]]`, which is nice.

The problem I have is that even when nobody passes any fileIds I get a `Some(List())` instead of a `None`. Any ideas?
